name: Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build Solution
      run: |
        cd code
        dotnet build SiteGenerator.sln --configuration Release

    - name: Run Tests
      run: |
        cd code
        dotnet test SiteGenerator.sln --no-build --configuration Release

    # Commented out deployment step until secrets are available
    # - name: Deploy to Cloudflare Pages
    #   env:
    #     CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    #   run: |
    #     cd StaticSiteGenerator
    #     dotnet run -- deploy
